version: '3.8'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    networks:
      - pconsi-network

networks:
  pconsi-network:
    driver: bridge
